//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthPolicyRefStatus) DeepCopyInto(out *AuthPolicyRefStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthPolicyRefStatus.
func (in *AuthPolicyRefStatus) DeepCopy() *AuthPolicyRefStatus {
	if in == nil {
		return nil
	}
	out := new(AuthPolicyRefStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingRate) DeepCopyInto(out *BillingRate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingRate.
func (in *BillingRate) DeepCopy() *BillingRate {
	if in == nil {
		return nil
	}
	out := new(BillingRate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupReference) DeepCopyInto(out *GroupReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupReference.
func (in *GroupReference) DeepCopy() *GroupReference {
	if in == nil {
		return nil
	}
	out := new(GroupReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaaSAuthPolicy) DeepCopyInto(out *MaaSAuthPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaaSAuthPolicy.
func (in *MaaSAuthPolicy) DeepCopy() *MaaSAuthPolicy {
	if in == nil {
		return nil
	}
	out := new(MaaSAuthPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaaSAuthPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaaSAuthPolicyList) DeepCopyInto(out *MaaSAuthPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MaaSAuthPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaaSAuthPolicyList.
func (in *MaaSAuthPolicyList) DeepCopy() *MaaSAuthPolicyList {
	if in == nil {
		return nil
	}
	out := new(MaaSAuthPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaaSAuthPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaaSAuthPolicySpec) DeepCopyInto(out *MaaSAuthPolicySpec) {
	*out = *in
	if in.ModelRefs != nil {
		in, out := &in.ModelRefs, &out.ModelRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Subjects.DeepCopyInto(&out.Subjects)
	if in.MeteringMetadata != nil {
		in, out := &in.MeteringMetadata, &out.MeteringMetadata
		*out = new(MeteringMetadata)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaaSAuthPolicySpec.
func (in *MaaSAuthPolicySpec) DeepCopy() *MaaSAuthPolicySpec {
	if in == nil {
		return nil
	}
	out := new(MaaSAuthPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaaSAuthPolicyStatus) DeepCopyInto(out *MaaSAuthPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AuthPolicies != nil {
		in, out := &in.AuthPolicies, &out.AuthPolicies
		*out = make([]AuthPolicyRefStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaaSAuthPolicyStatus.
func (in *MaaSAuthPolicyStatus) DeepCopy() *MaaSAuthPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(MaaSAuthPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaaSModelRef) DeepCopyInto(out *MaaSModelRef) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaaSModelRef.
func (in *MaaSModelRef) DeepCopy() *MaaSModelRef {
	if in == nil {
		return nil
	}
	out := new(MaaSModelRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaaSModelRef) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaaSModelRefList) DeepCopyInto(out *MaaSModelRefList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MaaSModelRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaaSModelRefList.
func (in *MaaSModelRefList) DeepCopy() *MaaSModelRefList {
	if in == nil {
		return nil
	}
	out := new(MaaSModelRefList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaaSModelRefList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaaSModelSpec) DeepCopyInto(out *MaaSModelSpec) {
	*out = *in
	out.ModelRef = in.ModelRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaaSModelSpec.
func (in *MaaSModelSpec) DeepCopy() *MaaSModelSpec {
	if in == nil {
		return nil
	}
	out := new(MaaSModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaaSModelStatus) DeepCopyInto(out *MaaSModelStatus) {
	*out = *in
	if in.HTTPRouteHostnames != nil {
		in, out := &in.HTTPRouteHostnames, &out.HTTPRouteHostnames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaaSModelStatus.
func (in *MaaSModelStatus) DeepCopy() *MaaSModelStatus {
	if in == nil {
		return nil
	}
	out := new(MaaSModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaaSSubscription) DeepCopyInto(out *MaaSSubscription) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaaSSubscription.
func (in *MaaSSubscription) DeepCopy() *MaaSSubscription {
	if in == nil {
		return nil
	}
	out := new(MaaSSubscription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaaSSubscription) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaaSSubscriptionList) DeepCopyInto(out *MaaSSubscriptionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MaaSSubscription, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaaSSubscriptionList.
func (in *MaaSSubscriptionList) DeepCopy() *MaaSSubscriptionList {
	if in == nil {
		return nil
	}
	out := new(MaaSSubscriptionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaaSSubscriptionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaaSSubscriptionSpec) DeepCopyInto(out *MaaSSubscriptionSpec) {
	*out = *in
	in.Owner.DeepCopyInto(&out.Owner)
	if in.ModelRefs != nil {
		in, out := &in.ModelRefs, &out.ModelRefs
		*out = make([]ModelSubscriptionRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TokenMetadata != nil {
		in, out := &in.TokenMetadata, &out.TokenMetadata
		*out = new(TokenMetadata)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaaSSubscriptionSpec.
func (in *MaaSSubscriptionSpec) DeepCopy() *MaaSSubscriptionSpec {
	if in == nil {
		return nil
	}
	out := new(MaaSSubscriptionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaaSSubscriptionStatus) DeepCopyInto(out *MaaSSubscriptionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaaSSubscriptionStatus.
func (in *MaaSSubscriptionStatus) DeepCopy() *MaaSSubscriptionStatus {
	if in == nil {
		return nil
	}
	out := new(MaaSSubscriptionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeteringMetadata) DeepCopyInto(out *MeteringMetadata) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeteringMetadata.
func (in *MeteringMetadata) DeepCopy() *MeteringMetadata {
	if in == nil {
		return nil
	}
	out := new(MeteringMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelReference) DeepCopyInto(out *ModelReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelReference.
func (in *ModelReference) DeepCopy() *ModelReference {
	if in == nil {
		return nil
	}
	out := new(ModelReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelSubscriptionRef) DeepCopyInto(out *ModelSubscriptionRef) {
	*out = *in
	if in.TokenRateLimits != nil {
		in, out := &in.TokenRateLimits, &out.TokenRateLimits
		*out = make([]TokenRateLimit, len(*in))
		copy(*out, *in)
	}
	if in.TokenRateLimitRef != nil {
		in, out := &in.TokenRateLimitRef, &out.TokenRateLimitRef
		*out = new(string)
		**out = **in
	}
	if in.BillingRate != nil {
		in, out := &in.BillingRate, &out.BillingRate
		*out = new(BillingRate)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelSubscriptionRef.
func (in *ModelSubscriptionRef) DeepCopy() *ModelSubscriptionRef {
	if in == nil {
		return nil
	}
	out := new(ModelSubscriptionRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OwnerSpec) DeepCopyInto(out *OwnerSpec) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]GroupReference, len(*in))
		copy(*out, *in)
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnerSpec.
func (in *OwnerSpec) DeepCopy() *OwnerSpec {
	if in == nil {
		return nil
	}
	out := new(OwnerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubjectSpec) DeepCopyInto(out *SubjectSpec) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]GroupReference, len(*in))
		copy(*out, *in)
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubjectSpec.
func (in *SubjectSpec) DeepCopy() *SubjectSpec {
	if in == nil {
		return nil
	}
	out := new(SubjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenMetadata) DeepCopyInto(out *TokenMetadata) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenMetadata.
func (in *TokenMetadata) DeepCopy() *TokenMetadata {
	if in == nil {
		return nil
	}
	out := new(TokenMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenRateLimit) DeepCopyInto(out *TokenRateLimit) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenRateLimit.
func (in *TokenRateLimit) DeepCopy() *TokenRateLimit {
	if in == nil {
		return nil
	}
	out := new(TokenRateLimit)
	in.DeepCopyInto(out)
	return out
}
