/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package maas

import (
	"context"
	"strings"
	"testing"

	apierrors "k8s.io/apimachinery/pkg/api/errors"
	apimeta "k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/types"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
	gatewayapiv1 "sigs.k8s.io/gateway-api/apis/v1"

	maasv1alpha1 "github.com/opendatahub-io/models-as-a-service/maas-controller/api/maas/v1alpha1"
)

// newPreexistingAuthPolicy builds a Kuadrant AuthPolicy as an unstructured object
// with a sentinel value in spec.targetRef.name. Tests use this to detect whether
// the controller overwrote the spec or left it untouched.
func newPreexistingAuthPolicy(name, namespace, modelName string, annotations map[string]string) *unstructured.Unstructured {
	ap := &unstructured.Unstructured{}
	ap.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
	ap.SetName(name)
	ap.SetNamespace(namespace)
	ap.SetLabels(map[string]string{
		"maas.opendatahub.io/model":    modelName,
		"app.kubernetes.io/managed-by": "maas-controller",
		"app.kubernetes.io/part-of":    "maas-auth-policy",
		"app.kubernetes.io/component":  "auth-policy",
	})
	ap.SetAnnotations(annotations)
	_ = unstructured.SetNestedField(ap.Object, "sentinel-route", "spec", "targetRef", "name")
	return ap
}

// TestMaaSAuthPolicyReconciler_ManagedAnnotation verifies the opt-out behaviour of the
// "opendatahub.io/managed" annotation on generated Kuadrant AuthPolicy resources.
//
// When the annotation is set to "false" on an existing AuthPolicy, the controller must
// leave the resource untouched. Any other value (or the annotation being absent) means
// the controller owns the resource and must overwrite its spec.
func TestMaaSAuthPolicyReconciler_ManagedAnnotation(t *testing.T) {
	const (
		modelName      = "llm"
		namespace      = "default"
		httpRouteName  = modelName                // ExternalModel naming convention
		authPolicyName = "maas-auth-" + modelName // generated by the controller
		maasPolicyName = "policy-a"
	)

	tests := []struct {
		name        string
		annotations map[string]string
		wantDeleted bool // true → controller should remove legacy per-model policy
	}{
		{
			name:        "annotation absent: controller deletes legacy per-model policy",
			annotations: map[string]string{},
			wantDeleted: true,
		},
		{
			name:        "opendatahub.io/managed=false: controller preserves opt-out policy",
			annotations: map[string]string{ManagedByODHOperator: "false"},
			wantDeleted: false,
		},
		{
			name:        "opendatahub.io/managed=true: controller deletes legacy per-model policy",
			annotations: map[string]string{ManagedByODHOperator: "true"},
			wantDeleted: true,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			model := newMaaSModelRef(modelName, namespace, "ExternalModel", modelName)
			route := newHTTPRoute(httpRouteName, namespace)
			maasPolicy := newMaaSAuthPolicy(maasPolicyName, namespace, "team-a", maasv1alpha1.ModelRef{Name: modelName, Namespace: namespace})
			// Pre-populate the store with a generated AuthPolicy whose spec contains a
			// sentinel targetRef. After reconciliation we check whether it changed.
			existingAP := newPreexistingAuthPolicy(authPolicyName, namespace, modelName, tc.annotations)

			c := fake.NewClientBuilder().
				WithScheme(scheme).
				WithRESTMapper(testRESTMapper()).
				WithObjects(model, route, maasPolicy, existingAP).
				WithStatusSubresource(&maasv1alpha1.MaaSAuthPolicy{}).
				Build()

			r := &MaaSAuthPolicyReconciler{Client: c, Scheme: scheme, MaaSAPINamespace: "maas-system"}
			req := ctrl.Request{NamespacedName: types.NamespacedName{Name: maasPolicyName, Namespace: namespace}}
			if _, err := r.Reconcile(context.Background(), req); err != nil {
				t.Fatalf("Reconcile: unexpected error: %v", err)
			}

			got := &unstructured.Unstructured{}
			got.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
			getErr := c.Get(context.Background(), types.NamespacedName{Name: authPolicyName, Namespace: namespace}, got)

			if tc.wantDeleted {
				if !apierrors.IsNotFound(getErr) {
					t.Fatalf("expected legacy per-model AuthPolicy to be deleted, got: %v", getErr)
				}
				return
			}
			if getErr != nil {
				t.Fatalf("expected opt-out AuthPolicy to survive reconciliation, got: %v", getErr)
			}
			// Managed=false still opts out from cleanup; sentinel confirms untouched spec.
			targetRefName, found, nestedErr := unstructured.NestedString(got.Object, "spec", "targetRef", "name")
			if nestedErr != nil || !found {
				t.Fatalf("spec.targetRef.name missing or invalid: found=%v err=%v", found, nestedErr)
			}
			if targetRefName != "sentinel-route" {
				t.Errorf("spec.targetRef.name = %q: expected sentinel %q (managed=false opt-out)", targetRefName, "sentinel-route")
			}
		})
	}
}

// TestMaaSAuthPolicyReconciler_DuplicateReconciliation verifies that reconciling
// multiple auth policies for the same model does not produce redundant AuthPolicy updates.
//
// When N auth policies reference the same model, each reconciliation builds the same
// aggregated AuthPolicy. The controller must skip the Update call when the content is
// identical to what already exists, otherwise each Update triggers a watch event that
// cascades into O(N²) reconciliations.
func TestMaaSAuthPolicyReconciler_DuplicateReconciliation(t *testing.T) {
	const (
		modelName     = "llm"
		namespace     = "default"
		httpRouteName = modelName
		gatewayNS     = "gateway-ns"
	)

	model := newMaaSModelRef(modelName, namespace, "ExternalModel", modelName)
	route := newHTTPRoute(httpRouteName, namespace)
	policyA := newMaaSAuthPolicy("policy-a", namespace, "team-a", maasv1alpha1.ModelRef{Name: modelName, Namespace: namespace})
	policyB := newMaaSAuthPolicy("policy-b", namespace, "team-b", maasv1alpha1.ModelRef{Name: modelName, Namespace: namespace})

	c := fake.NewClientBuilder().
		WithScheme(scheme).
		WithRESTMapper(testRESTMapper()).
		WithObjects(model, route, policyA, policyB).
		WithStatusSubresource(&maasv1alpha1.MaaSAuthPolicy{}).
		Build()

	r := &MaaSAuthPolicyReconciler{
		Client:           c,
		Scheme:           scheme,
		MaaSAPINamespace: "maas-system",
		GatewayNamespace: gatewayNS,
		GatewayName:      "maas-default-gateway",
	}
	ctx := context.Background()

	// Reconcile policy-a: creates the aggregated AuthPolicy (covering both policy-a and policy-b).
	reqA := ctrl.Request{NamespacedName: types.NamespacedName{Name: "policy-a", Namespace: namespace}}
	if _, err := r.Reconcile(ctx, reqA); err != nil {
		t.Fatalf("Reconcile policy-a: %v", err)
	}

	// Capture gateway AuthPolicy ResourceVersion after first reconciliation.
	ap := &unstructured.Unstructured{}
	ap.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
	if err := c.Get(ctx, types.NamespacedName{Name: "maas-gateway-auth", Namespace: gatewayNS}, ap); err != nil {
		t.Fatalf("Get gateway AuthPolicy after policy-a reconcile: %v", err)
	}
	rvAfterA := ap.GetResourceVersion()

	// Reconcile policy-b: both policies are still present, so the aggregated AuthPolicy
	// content is identical. The controller should detect this and skip the Update.
	reqB := ctrl.Request{NamespacedName: types.NamespacedName{Name: "policy-b", Namespace: namespace}}
	if _, err := r.Reconcile(ctx, reqB); err != nil {
		t.Fatalf("Reconcile policy-b: %v", err)
	}

	if err := c.Get(ctx, types.NamespacedName{Name: "maas-gateway-auth", Namespace: gatewayNS}, ap); err != nil {
		t.Fatalf("Get gateway AuthPolicy after policy-b reconcile: %v", err)
	}
	rvAfterB := ap.GetResourceVersion()

	if rvAfterA != rvAfterB {
		t.Errorf("redundant AuthPolicy update: ResourceVersion changed from %s to %s; "+
			"reconciling policy-b should not update the AuthPolicy when content is identical to policy-a's reconciliation",
			rvAfterA, rvAfterB)
	}
}

// TestMaaSAuthPolicyReconciler_DeleteAnnotation verifies that the Reconcile deletion
// path respects the opt-out annotation: an AuthPolicy with opendatahub.io/managed=false
// must not be deleted when the parent MaaSAuthPolicy is removed.
func TestMaaSAuthPolicyReconciler_DeleteAnnotation(t *testing.T) {
	const (
		modelName      = "llm"
		namespace      = "default"
		authPolicyName = "maas-auth-" + modelName
		maasPolicyName = "policy-a"
	)

	tests := []struct {
		name        string
		annotations map[string]string
		wantDeleted bool
	}{
		{
			name:        "annotation absent: controller deletes",
			annotations: map[string]string{},
			wantDeleted: true,
		},
		{
			name:        "opendatahub.io/managed=true: controller deletes",
			annotations: map[string]string{ManagedByODHOperator: "true"},
			wantDeleted: true,
		},
		{
			name:        "opendatahub.io/managed=false: controller must not delete",
			annotations: map[string]string{ManagedByODHOperator: "false"},
			wantDeleted: false,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			existingAP := newPreexistingAuthPolicy(authPolicyName, namespace, modelName, tc.annotations)

			// Create MaaSAuthPolicy with finalizer so handleDeletion processes it.
			maasPolicy := newMaaSAuthPolicy(maasPolicyName, namespace, "team-a", maasv1alpha1.ModelRef{Name: modelName, Namespace: namespace})
			maasPolicy.Finalizers = []string{maasAuthPolicyFinalizer}

			c := fake.NewClientBuilder().
				WithScheme(scheme).
				WithRESTMapper(testRESTMapper()).
				WithObjects(maasPolicy, existingAP).
				Build()

			// Simulate deletion: the fake client sets DeletionTimestamp while the
			// finalizer keeps the object in the store.
			if err := c.Delete(context.Background(), maasPolicy); err != nil {
				t.Fatalf("Delete MaaSAuthPolicy: %v", err)
			}

			r := &MaaSAuthPolicyReconciler{Client: c, Scheme: scheme, MaaSAPINamespace: "maas-system"}
			req := ctrl.Request{NamespacedName: types.NamespacedName{Name: maasPolicyName, Namespace: namespace}}
			if _, err := r.Reconcile(context.Background(), req); err != nil {
				t.Fatalf("Reconcile: unexpected error: %v", err)
			}

			got := &unstructured.Unstructured{}
			got.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
			err := c.Get(context.Background(), types.NamespacedName{Name: authPolicyName, Namespace: namespace}, got)

			if tc.wantDeleted {
				if !apierrors.IsNotFound(err) {
					t.Errorf("expected AuthPolicy %q to be deleted, but it still exists", authPolicyName)
				}
			} else {
				if err != nil {
					t.Errorf("expected AuthPolicy %q to survive deletion (managed=false opt-out), but got: %v", authPolicyName, err)
				}
			}
		})
	}
}

// TestMaaSAuthPolicyReconciler_RemoveModelRef verifies that removing a modelRef from
// a MaaSAuthPolicy deletes the aggregated AuthPolicy for the removed model while
// keeping the AuthPolicy for the remaining model intact.
func TestMaaSAuthPolicyReconciler_RemoveModelRef(t *testing.T) {
	const (
		modelA         = "model-a"
		modelB         = "model-b"
		namespace      = "default"
		httpRouteA     = modelA
		httpRouteB     = modelB
		authPolicyA    = "maas-auth-" + modelA
		authPolicyB    = "maas-auth-" + modelB
		maasPolicyName = "policy-1"
		gatewayNS      = "gateway-ns"
	)

	modelRefA := newMaaSModelRef(modelA, namespace, "ExternalModel", modelA)
	modelRefB := newMaaSModelRef(modelB, namespace, "ExternalModel", modelB)
	routeA := newHTTPRoute(httpRouteA, namespace)
	routeB := newHTTPRoute(httpRouteB, namespace)

	maasPolicy := newMaaSAuthPolicy(maasPolicyName, namespace, "team-a",
		maasv1alpha1.ModelRef{Name: modelA, Namespace: namespace},
		maasv1alpha1.ModelRef{Name: modelB, Namespace: namespace},
	)

	c := fake.NewClientBuilder().
		WithScheme(scheme).
		WithRESTMapper(testRESTMapper()).
		WithObjects(modelRefA, modelRefB, routeA, routeB, maasPolicy).
		WithStatusSubresource(&maasv1alpha1.MaaSAuthPolicy{}).
		Build()

	r := &MaaSAuthPolicyReconciler{
		Client:           c,
		Scheme:           scheme,
		MaaSAPINamespace: "maas-system",
		GatewayNamespace: gatewayNS,
		GatewayName:      "maas-default-gateway",
	}
	ctx := context.Background()
	req := ctrl.Request{NamespacedName: types.NamespacedName{Name: maasPolicyName, Namespace: namespace}}

	if _, err := r.Reconcile(ctx, req); err != nil {
		t.Fatalf("Initial reconcile: %v", err)
	}

	// Legacy per-model AuthPolicies should not exist in gateway-only mode.
	for _, name := range []string{authPolicyA, authPolicyB} {
		ap := &unstructured.Unstructured{}
		ap.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
		if err := c.Get(ctx, types.NamespacedName{Name: name, Namespace: namespace}, ap); !apierrors.IsNotFound(err) {
			t.Fatalf("legacy per-model AuthPolicy %q should be absent, got: %v", name, err)
		}
	}

	// Remove model B from the policy
	freshPolicy := &maasv1alpha1.MaaSAuthPolicy{}
	if err := c.Get(ctx, types.NamespacedName{Name: maasPolicyName, Namespace: namespace}, freshPolicy); err != nil {
		t.Fatalf("Get MaaSAuthPolicy: %v", err)
	}
	freshPolicy.Spec.ModelRefs = []maasv1alpha1.ModelRef{{Name: modelA, Namespace: namespace}}
	if err := c.Update(ctx, freshPolicy); err != nil {
		t.Fatalf("Update MaaSAuthPolicy: %v", err)
	}

	if _, err := r.Reconcile(ctx, req); err != nil {
		t.Fatalf("Reconcile after removing modelRef: %v", err)
	}

	// Legacy per-model AuthPolicies should remain absent.
	for _, name := range []string{authPolicyA, authPolicyB} {
		ap := &unstructured.Unstructured{}
		ap.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
		err := c.Get(ctx, types.NamespacedName{Name: name, Namespace: namespace}, ap)
		if !apierrors.IsNotFound(err) {
			t.Errorf("legacy per-model AuthPolicy %q should be absent, got: %v", name, err)
		}
	}

	// Gateway policy should only carry model A after model B is removed.
	gw := &unstructured.Unstructured{}
	gw.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
	if err := c.Get(ctx, types.NamespacedName{Name: "maas-gateway-auth", Namespace: gatewayNS}, gw); err != nil {
		t.Fatalf("Get gateway AuthPolicy: %v", err)
	}
	rego, found, err := unstructured.NestedString(gw.Object, "spec", "defaults", "rules", "authorization", "require-group-membership", "opa", "rego")
	if err != nil || !found {
		t.Fatalf("gateway require-group-membership rego missing: found=%v err=%v", found, err)
	}
	if !contains(rego, namespace+"/"+modelA) {
		t.Errorf("gateway rego should include %q", namespace+"/"+modelA)
	}
	if contains(rego, namespace+"/"+modelB) {
		t.Errorf("gateway rego should not include removed model %q", namespace+"/"+modelB)
	}
}

// TestMaaSAuthPolicyReconciler_RemoveModelRef_Aggregation verifies that when one policy
// drops a model that another policy still references, the aggregated AuthPolicy is deleted
// (forcing a rebuild by the remaining policy) without affecting unrelated models.
func TestMaaSAuthPolicyReconciler_RemoveModelRef_Aggregation(t *testing.T) {
	const (
		modelA     = "model-a"
		modelB     = "model-b"
		namespace  = "default"
		httpRouteA = modelA
		httpRouteB = modelB
		gatewayNS  = "gateway-ns"
	)

	modelRefA := newMaaSModelRef(modelA, namespace, "ExternalModel", modelA)
	modelRefB := newMaaSModelRef(modelB, namespace, "ExternalModel", modelB)
	routeA := newHTTPRoute(httpRouteA, namespace)
	routeB := newHTTPRoute(httpRouteB, namespace)

	// ap1 references [A, B], ap2 references [B]
	ap1 := newMaaSAuthPolicy("ap1", namespace, "team-1",
		maasv1alpha1.ModelRef{Name: modelA, Namespace: namespace},
		maasv1alpha1.ModelRef{Name: modelB, Namespace: namespace},
	)
	ap2 := newMaaSAuthPolicy("ap2", namespace, "team-2",
		maasv1alpha1.ModelRef{Name: modelB, Namespace: namespace},
	)

	c := fake.NewClientBuilder().
		WithScheme(scheme).
		WithRESTMapper(testRESTMapper()).
		WithObjects(modelRefA, modelRefB, routeA, routeB, ap1, ap2).
		WithStatusSubresource(&maasv1alpha1.MaaSAuthPolicy{}).
		Build()

	r := &MaaSAuthPolicyReconciler{
		Client:           c,
		Scheme:           scheme,
		MaaSAPINamespace: "maas-system",
		GatewayNamespace: gatewayNS,
		GatewayName:      "maas-default-gateway",
	}
	ctx := context.Background()

	// Reconcile both policies to create aggregated AuthPolicies
	req1 := ctrl.Request{NamespacedName: types.NamespacedName{Name: "ap1", Namespace: namespace}}
	req2 := ctrl.Request{NamespacedName: types.NamespacedName{Name: "ap2", Namespace: namespace}}
	if _, err := r.Reconcile(ctx, req1); err != nil {
		t.Fatalf("Reconcile ap1: %v", err)
	}
	if _, err := r.Reconcile(ctx, req2); err != nil {
		t.Fatalf("Reconcile ap2: %v", err)
	}

	// Remove model B from ap1 (ap2 still references it)
	freshAP1 := &maasv1alpha1.MaaSAuthPolicy{}
	if err := c.Get(ctx, types.NamespacedName{Name: "ap1", Namespace: namespace}, freshAP1); err != nil {
		t.Fatalf("Get ap1: %v", err)
	}
	freshAP1.Spec.ModelRefs = []maasv1alpha1.ModelRef{{Name: modelA, Namespace: namespace}}
	if err := c.Update(ctx, freshAP1); err != nil {
		t.Fatalf("Update ap1: %v", err)
	}

	// Reconcile ap1 and verify model B is still aggregated via ap2.
	if _, err := r.Reconcile(ctx, req1); err != nil {
		t.Fatalf("Reconcile ap1 after removing modelRef: %v", err)
	}
	gw := &unstructured.Unstructured{}
	gw.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
	if err := c.Get(ctx, types.NamespacedName{Name: "maas-gateway-auth", Namespace: gatewayNS}, gw); err != nil {
		t.Fatalf("Get gateway AuthPolicy: %v", err)
	}
	rego, found, err := unstructured.NestedString(gw.Object, "spec", "defaults", "rules", "authorization", "require-group-membership", "opa", "rego")
	if err != nil || !found {
		t.Fatalf("gateway require-group-membership rego missing: found=%v err=%v", found, err)
	}
	if !contains(rego, namespace+"/"+modelB) {
		t.Fatalf("model B should remain aggregated while ap2 still references it")
	}

	// Delete ap2 and reconcile deletion; model B should then disappear from aggregate.
	freshAP2 := &maasv1alpha1.MaaSAuthPolicy{}
	if err := c.Get(ctx, types.NamespacedName{Name: "ap2", Namespace: namespace}, freshAP2); err != nil {
		t.Fatalf("Get ap2: %v", err)
	}
	if err := c.Delete(ctx, freshAP2); err != nil {
		t.Fatalf("Delete ap2: %v", err)
	}
	if _, err := r.Reconcile(ctx, req2); err != nil {
		t.Fatalf("Reconcile ap2 deletion: %v", err)
	}
	// Deletion reconcile does cleanup/finalizer handling; run ap1 reconcile to
	// rebuild the gateway aggregate from surviving policies.
	if _, err := r.Reconcile(ctx, req1); err != nil {
		t.Fatalf("Reconcile ap1 after ap2 deletion: %v", err)
	}
	if err := c.Get(ctx, types.NamespacedName{Name: "maas-gateway-auth", Namespace: gatewayNS}, gw); err != nil {
		t.Fatalf("Get gateway AuthPolicy after ap2 deletion: %v", err)
	}
	rego, found, err = unstructured.NestedString(gw.Object, "spec", "defaults", "rules", "authorization", "require-group-membership", "opa", "rego")
	if err != nil || !found {
		t.Fatalf("gateway require-group-membership rego missing after ap2 deletion: found=%v err=%v", found, err)
	}
	if contains(rego, namespace+"/"+modelB) {
		t.Errorf("model B should be removed from aggregate after deleting ap2")
	}
	if !contains(rego, namespace+"/"+modelA) {
		t.Errorf("model A should still be present after deleting ap2")
	}
}

// TestMaaSAuthPolicyReconciler_MultiplePoliciesDeletion verifies that when multiple
// MaaSAuthPolicies reference the same model, deleting one does not delete the aggregated
// AuthPolicy, but deleting the last one does.
func TestMaaSAuthPolicyReconciler_MultiplePoliciesDeletion(t *testing.T) {
	const (
		modelName      = "shared-model"
		modelNamespace = "llm"
		httpRouteName  = modelName
		policy1Name    = "policy-1"
		policy2Name    = "policy-2"
		policyNS       = "opendatahub"
		gatewayNS      = "gateway-ns"
	)

	// Create model and HTTPRoute
	model := &maasv1alpha1.MaaSModelRef{
		ObjectMeta: metav1.ObjectMeta{Name: modelName, Namespace: modelNamespace},
		Spec: maasv1alpha1.MaaSModelSpec{
			ModelRef: maasv1alpha1.ModelReference{Kind: "ExternalModel", Name: modelName},
		},
	}
	route := &gatewayapiv1.HTTPRoute{
		ObjectMeta: metav1.ObjectMeta{Name: httpRouteName, Namespace: modelNamespace},
	}

	// Create two MaaSAuthPolicies both referencing the same model
	policy1 := &maasv1alpha1.MaaSAuthPolicy{
		ObjectMeta: metav1.ObjectMeta{
			Name:       policy1Name,
			Namespace:  policyNS,
			Finalizers: []string{maasAuthPolicyFinalizer},
		},
		Spec: maasv1alpha1.MaaSAuthPolicySpec{
			ModelRefs: []maasv1alpha1.ModelRef{{Name: modelName, Namespace: modelNamespace}},
			Subjects:  maasv1alpha1.SubjectSpec{Groups: []maasv1alpha1.GroupReference{{Name: "team-1"}}},
		},
	}
	policy2 := &maasv1alpha1.MaaSAuthPolicy{
		ObjectMeta: metav1.ObjectMeta{
			Name:       policy2Name,
			Namespace:  policyNS,
			Finalizers: []string{maasAuthPolicyFinalizer},
		},
		Spec: maasv1alpha1.MaaSAuthPolicySpec{
			ModelRefs: []maasv1alpha1.ModelRef{{Name: modelName, Namespace: modelNamespace}},
			Subjects:  maasv1alpha1.SubjectSpec{Groups: []maasv1alpha1.GroupReference{{Name: "team-2"}}},
		},
	}

	// Pre-create gateway-default-auth (deployed by Tenant reconciler in real clusters)
	gwDefaultAuth := &unstructured.Unstructured{}
	gwDefaultAuth.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
	gwDefaultAuth.SetName(gatewayDefaultAuthPolicyName)
	gwDefaultAuth.SetNamespace(gatewayNS)
	gwDefaultAuth.SetLabels(map[string]string{
		"app.kubernetes.io/managed-by": "maas-controller",
	})

	c := fake.NewClientBuilder().
		WithScheme(scheme).
		WithRESTMapper(testRESTMapper()).
		WithObjects(model, route, policy1, policy2, gwDefaultAuth).
		WithStatusSubresource(&maasv1alpha1.MaaSAuthPolicy{}).
		Build()

	r := &MaaSAuthPolicyReconciler{
		Client:           c,
		Scheme:           scheme,
		MaaSAPINamespace: "maas-system",
		GatewayNamespace: gatewayNS,
		GatewayName:      "maas-default-gateway",
	}

	// Verify gateway-default-auth exists before reconciliation
	defaultAuth := &unstructured.Unstructured{}
	defaultAuth.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
	if err := c.Get(context.Background(), types.NamespacedName{Name: gatewayDefaultAuthPolicyName, Namespace: gatewayNS}, defaultAuth); err != nil {
		t.Fatalf("gateway-default-auth should exist before reconciliation: %v", err)
	}

	// Reconcile both policies to create the aggregated AuthPolicy
	req1 := ctrl.Request{NamespacedName: types.NamespacedName{Name: policy1Name, Namespace: policyNS}}
	if _, err := r.Reconcile(context.Background(), req1); err != nil {
		t.Fatalf("Reconcile policy1: %v", err)
	}
	req2 := ctrl.Request{NamespacedName: types.NamespacedName{Name: policy2Name, Namespace: policyNS}}
	if _, err := r.Reconcile(context.Background(), req2); err != nil {
		t.Fatalf("Reconcile policy2: %v", err)
	}

	// Verify gateway AuthPolicy was created
	authPolicy := &unstructured.Unstructured{}
	authPolicy.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
	if err := c.Get(context.Background(), types.NamespacedName{Name: "maas-gateway-auth", Namespace: gatewayNS}, authPolicy); err != nil {
		t.Fatalf("gateway AuthPolicy not found before deletion: %v", err)
	}

	// Verify gateway-default-auth was DELETED (superseded by maas-gateway-auth)
	defaultAuth = &unstructured.Unstructured{}
	defaultAuth.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
	if err := c.Get(context.Background(), types.NamespacedName{Name: gatewayDefaultAuthPolicyName, Namespace: gatewayNS}, defaultAuth); !apierrors.IsNotFound(err) {
		t.Errorf("gateway-default-auth should be deleted when maas-gateway-auth exists, got: %v", err)
	}

	// Delete policy1 (but policy2 still exists)
	if err := c.Delete(context.Background(), policy1); err != nil {
		t.Fatalf("Delete policy1: %v", err)
	}
	// Reconcile policy1 deletion; gateway policy should still exist due to policy2.
	if _, err := r.Reconcile(context.Background(), req1); err != nil {
		t.Fatalf("Reconcile policy1 deletion: %v", err)
	}
	if err := c.Get(context.Background(), types.NamespacedName{Name: "maas-gateway-auth", Namespace: gatewayNS}, authPolicy); err != nil {
		t.Fatalf("gateway AuthPolicy should persist while policy2 exists: %v", err)
	}

	// Now delete policy2 (the last one)
	if err := c.Delete(context.Background(), policy2); err != nil {
		t.Fatalf("Delete policy2: %v", err)
	}
	if _, err := r.Reconcile(context.Background(), req2); err != nil {
		t.Fatalf("Reconcile policy2 deletion: %v", err)
	}

	// Gateway AuthPolicy should NOW BE DELETED (no remaining parents).
	authPolicy = &unstructured.Unstructured{}
	authPolicy.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
	err := c.Get(context.Background(), types.NamespacedName{Name: "maas-gateway-auth", Namespace: gatewayNS}, authPolicy)
	if !apierrors.IsNotFound(err) {
		t.Errorf("gateway AuthPolicy should be deleted after deleting last parent policy, but got: %v", err)
	}

	// gateway-default-auth should be RECREATED (deny-all restored for unconfigured models)
	defaultAuth = &unstructured.Unstructured{}
	defaultAuth.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
	if err := c.Get(context.Background(), types.NamespacedName{Name: gatewayDefaultAuthPolicyName, Namespace: gatewayNS}, defaultAuth); err != nil {
		t.Errorf("gateway-default-auth should be recreated after last MaaSAuthPolicy is deleted: %v", err)
	}
}

// TestMaaSAuthPolicyReconciler_CachingConfiguration verifies that the controller
// generates cache blocks on metadata and authorization evaluators with configurable TTLs.
//
// In gateway-only mode all authorization evaluators, including require-group-membership,
// live in the singleton gateway AuthPolicy.
func TestMaaSAuthPolicyReconciler_CachingConfiguration(t *testing.T) {
	const (
		modelName      = "llm"
		namespace      = "default"
		gatewayNS      = "gateway-ns"
		httpRouteName  = modelName
		maasPolicyName = "policy-a"
	)

	tests := []struct {
		name            string
		metadataTTL     int64
		authzTTL        int64
		wantMetadataTTL int64
		wantAuthzTTL    int64
	}{
		{
			name:            "default TTLs (60s)",
			metadataTTL:     60,
			authzTTL:        60,
			wantMetadataTTL: 60,
			wantAuthzTTL:    60,
		},
		{
			name:            "custom metadata TTL (300s)",
			metadataTTL:     300,
			authzTTL:        60,
			wantMetadataTTL: 300,
			wantAuthzTTL:    60,
		},
		{
			name:            "custom authz TTL (30s)",
			metadataTTL:     60,
			authzTTL:        30,
			wantMetadataTTL: 60,
			wantAuthzTTL:    30,
		},
		{
			name:            "both custom (5min metadata, 1min authz)",
			metadataTTL:     300,
			authzTTL:        60,
			wantMetadataTTL: 300,
			wantAuthzTTL:    60,
		},
		{
			name:            "authz TTL capped at metadata TTL (authz=300, metadata=60)",
			metadataTTL:     60,
			authzTTL:        300,
			wantMetadataTTL: 60,
			wantAuthzTTL:    60, // Should be capped at metadata TTL
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			model := newMaaSModelRef(modelName, namespace, "ExternalModel", modelName)
			route := newHTTPRoute(httpRouteName, namespace)
			maasPolicy := newMaaSAuthPolicy(maasPolicyName, namespace, "team-a", maasv1alpha1.ModelRef{Name: modelName, Namespace: namespace})

			c := fake.NewClientBuilder().
				WithScheme(scheme).
				WithRESTMapper(testRESTMapper()).
				WithObjects(model, route, maasPolicy).
				WithStatusSubresource(&maasv1alpha1.MaaSAuthPolicy{}).
				Build()

			r := &MaaSAuthPolicyReconciler{
				Client:           c,
				Scheme:           scheme,
				MaaSAPINamespace: "maas-system",
				GatewayName:      "maas-default-gateway",
				GatewayNamespace: gatewayNS,
				MetadataCacheTTL: tc.metadataTTL,
				AuthzCacheTTL:    tc.authzTTL,
			}

			req := ctrl.Request{NamespacedName: types.NamespacedName{Name: maasPolicyName, Namespace: namespace}}
			if _, err := r.Reconcile(context.Background(), req); err != nil {
				t.Fatalf("Reconcile: unexpected error: %v", err)
			}

			// Gateway policy holds metadata + auth-valid + subscription-valid
			gwPolicy := &unstructured.Unstructured{}
			gwPolicy.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
			if err := c.Get(context.Background(), types.NamespacedName{Name: "maas-gateway-auth", Namespace: gatewayNS}, gwPolicy); err != nil {
				t.Fatalf("Get gateway AuthPolicy %q: %v", "maas-gateway-auth", err)
			}

			// Verify apiKeyValidation metadata has cache with correct TTL (on gateway policy)
			apiKeyValTTL, found, err := unstructured.NestedInt64(gwPolicy.Object, "spec", "defaults", "rules", "metadata", "apiKeyValidation", "cache", "ttl")
			if err != nil || !found {
				t.Errorf("apiKeyValidation cache.ttl missing or invalid: found=%v err=%v", found, err)
			} else if apiKeyValTTL != tc.wantMetadataTTL {
				t.Errorf("apiKeyValidation cache.ttl = %d, want %d", apiKeyValTTL, tc.wantMetadataTTL)
			}

			// Verify apiKeyValidation has cache key (on gateway policy)
			apiKeyValCacheKey, found, err := unstructured.NestedString(gwPolicy.Object, "spec", "defaults", "rules", "metadata", "apiKeyValidation", "cache", "key", "selector")
			if err != nil || !found {
				t.Errorf("apiKeyValidation cache.key.selector missing: found=%v err=%v", found, err)
			} else if apiKeyValCacheKey == "" {
				t.Errorf("apiKeyValidation cache.key.selector is empty")
			}

			// Verify subscription-info metadata has cache with correct TTL (on gateway policy)
			subInfoTTL, found, err := unstructured.NestedInt64(gwPolicy.Object, "spec", "defaults", "rules", "metadata", "subscription-info", "cache", "ttl")
			if err != nil || !found {
				t.Errorf("subscription-info cache.ttl missing or invalid: found=%v err=%v", found, err)
			} else if subInfoTTL != tc.wantMetadataTTL {
				t.Errorf("subscription-info cache.ttl = %d, want %d", subInfoTTL, tc.wantMetadataTTL)
			}

			// Verify auth-valid authorization has cache with correct TTL (on gateway policy)
			authValidTTL, found, err := unstructured.NestedInt64(gwPolicy.Object, "spec", "defaults", "rules", "authorization", "auth-valid", "cache", "ttl")
			if err != nil || !found {
				t.Errorf("auth-valid cache.ttl missing or invalid: found=%v err=%v", found, err)
			} else if authValidTTL != tc.wantAuthzTTL {
				t.Errorf("auth-valid cache.ttl = %d, want %d", authValidTTL, tc.wantAuthzTTL)
			}

			// Verify subscription-valid authorization has cache with correct TTL (on gateway policy)
			subValidTTL, found, err := unstructured.NestedInt64(gwPolicy.Object, "spec", "defaults", "rules", "authorization", "subscription-valid", "cache", "ttl")
			if err != nil || !found {
				t.Errorf("subscription-valid cache.ttl missing or invalid: found=%v err=%v", found, err)
			} else if subValidTTL != tc.wantAuthzTTL {
				t.Errorf("subscription-valid cache.ttl = %d, want %d", subValidTTL, tc.wantAuthzTTL)
			}

			// Verify require-group-membership authorization has cache with correct TTL (on gateway policy)
			groupMembershipTTL, found, err := unstructured.NestedInt64(gwPolicy.Object, "spec", "defaults", "rules", "authorization", "require-group-membership", "cache", "ttl")
			if err != nil || !found {
				t.Errorf("require-group-membership cache.ttl missing or invalid: found=%v err=%v", found, err)
			} else if groupMembershipTTL != tc.wantAuthzTTL {
				t.Errorf("require-group-membership cache.ttl = %d, want %d", groupMembershipTTL, tc.wantAuthzTTL)
			}

			// Verify cache keys are present and non-empty (on gateway policy)
			authValidCacheKey, found, err := unstructured.NestedString(gwPolicy.Object, "spec", "defaults", "rules", "authorization", "auth-valid", "cache", "key", "selector")
			if err != nil || !found {
				t.Errorf("auth-valid cache.key.selector missing: found=%v err=%v", found, err)
			} else if authValidCacheKey == "" {
				t.Errorf("auth-valid cache.key.selector is empty")
			}

			subValidCacheKey, found, err := unstructured.NestedString(gwPolicy.Object, "spec", "defaults", "rules", "authorization", "subscription-valid", "cache", "key", "selector")
			if err != nil || !found {
				t.Errorf("subscription-valid cache.key.selector missing: found=%v err=%v", found, err)
			} else if subValidCacheKey == "" {
				t.Errorf("subscription-valid cache.key.selector is empty")
			}

			groupMembershipCacheKey, found, err := unstructured.NestedString(gwPolicy.Object, "spec", "defaults", "rules", "authorization", "require-group-membership", "cache", "key", "selector")
			if err != nil || !found {
				t.Errorf("require-group-membership cache.key.selector missing: found=%v err=%v", found, err)
			} else if groupMembershipCacheKey == "" {
				t.Errorf("require-group-membership cache.key.selector is empty")
			}
		})
	}
}

// TestMaaSAuthPolicyReconciler_NegativeTTLRejection verifies that the controller
// rejects negative cache TTL values at setup time.
func TestMaaSAuthPolicyReconciler_NegativeTTLRejection(t *testing.T) {
	tests := []struct {
		name            string
		metadataTTL     int64
		authzTTL        int64
		expectSetupFail bool
	}{
		{
			name:            "positive TTLs allowed",
			metadataTTL:     60,
			authzTTL:        30,
			expectSetupFail: false,
		},
		{
			name:            "zero TTLs allowed",
			metadataTTL:     0,
			authzTTL:        0,
			expectSetupFail: false,
		},
		{
			name:            "negative metadata TTL rejected",
			metadataTTL:     -10,
			authzTTL:        60,
			expectSetupFail: true,
		},
		{
			name:            "negative authz TTL rejected",
			metadataTTL:     60,
			authzTTL:        -10,
			expectSetupFail: true,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			r := &MaaSAuthPolicyReconciler{
				MetadataCacheTTL: tc.metadataTTL,
				AuthzCacheTTL:    tc.authzTTL,
			}

			// Test the validation logic used by SetupWithManager
			err := r.ValidateCacheTTLs()

			if tc.expectSetupFail {
				if err == nil {
					t.Errorf("Expected validation to fail for negative TTLs, but got no error")
				}
			} else {
				if err != nil {
					t.Errorf("Expected validation to succeed, but got error: %v", err)
				}

				// Also verify authzCacheTTL() defensive clamp never returns negative
				effectiveTTL := r.authzCacheTTL()
				if effectiveTTL < 0 {
					t.Errorf("authzCacheTTL() returned negative value %d, should be clamped to 0", effectiveTTL)
				}
			}
		})
	}
}

// TestMaaSAuthPolicyReconciler_CacheKeyIsolation verifies that cache keys include
// the necessary dimensions to prevent cross-principal or cross-model cache sharing.
//
// After the gateway-level AuthPolicy refactor the key structure changes:
//   - Gateway policy: apiKeyValidation, subscription-info, auth-valid, subscription-valid
//     use dynamic CEL (celModelIdentity) for runtime model isolation
//   - Group policy: require-group-membership uses static model namespace/name in the key
//
// This is a security-critical test: incorrect cache keys could leak authentication
// or authorization results between different users, API keys, or models.
func TestMaaSAuthPolicyReconciler_CacheKeyIsolation(t *testing.T) {
	const (
		modelName      = "llm"
		namespace      = "default"
		gatewayNS      = "gateway-ns"
		httpRouteName  = modelName
		maasPolicyName = "policy-a"
	)

	model := newMaaSModelRef(modelName, namespace, "ExternalModel", modelName)
	route := newHTTPRoute(httpRouteName, namespace)
	maasPolicy := newMaaSAuthPolicy(maasPolicyName, namespace, "team-a", maasv1alpha1.ModelRef{Name: modelName, Namespace: namespace})

	c := fake.NewClientBuilder().
		WithScheme(scheme).
		WithRESTMapper(testRESTMapper()).
		WithObjects(model, route, maasPolicy).
		WithStatusSubresource(&maasv1alpha1.MaaSAuthPolicy{}).
		Build()

	r := &MaaSAuthPolicyReconciler{
		Client:           c,
		Scheme:           scheme,
		MaaSAPINamespace: "maas-system",
		GatewayName:      "maas-default-gateway",
		GatewayNamespace: gatewayNS,
		MetadataCacheTTL: 60,
		AuthzCacheTTL:    60,
	}

	req := ctrl.Request{NamespacedName: types.NamespacedName{Name: maasPolicyName, Namespace: namespace}}
	if _, err := r.Reconcile(context.Background(), req); err != nil {
		t.Fatalf("Reconcile: unexpected error: %v", err)
	}

	// Gateway policy holds apiKeyValidation, subscription-info, auth-valid, subscription-valid
	gwPolicy := &unstructured.Unstructured{}
	gwPolicy.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
	if err := c.Get(context.Background(), types.NamespacedName{Name: "maas-gateway-auth", Namespace: gatewayNS}, gwPolicy); err != nil {
		t.Fatalf("Get gateway AuthPolicy: %v", err)
	}

	// Test 1: apiKeyValidation cache key must include API key material (gateway policy)
	t.Run("apiKeyValidation includes API key", func(t *testing.T) {
		assertCacheKeyContains(t, gwPolicy,
			[]string{"request.headers.authorization", `replace("Bearer ", "")`},
			"spec", "defaults", "rules", "metadata", "apiKeyValidation", "cache", "key", "selector",
		)
	})

	// Test 2: subscription-info cache key must include userId, username, groups, and dynamic model identity (gateway policy)
	t.Run("subscription-info includes username, groups, model", func(t *testing.T) {
		key := assertCacheKeyContains(t, gwPolicy,
			[]string{"userId", "username", "groups", "join"},
			"spec", "defaults", "rules", "metadata", "subscription-info", "cache", "key", "selector",
		)
		// Model identity is dynamic via CEL (X-Gateway-Model-Name header or path extraction).
		if !contains(key, "x-gateway-model-name") && !contains(key, "request.path") {
			t.Errorf("subscription-info cache key must include dynamic model identity (header or path), got: %s", key)
		}
	})

	// Test 3: auth-valid cache key must include API key identity and model (gateway policy)
	t.Run("auth-valid includes API key identity and model", func(t *testing.T) {
		key := assertCacheKeyContains(t, gwPolicy,
			nil,
			"spec", "defaults", "rules", "authorization", "auth-valid", "cache", "key", "selector",
		)
		if !contains(key, "api-key") {
			t.Errorf("auth-valid cache key must include api-key prefix, got: %s", key)
		}
		if !contains(key, "x-gateway-model-name") && !contains(key, "request.path") {
			t.Errorf("auth-valid cache key must include dynamic model identity (header or path), got: %s", key)
		}
		if !contains(key, "authorization") {
			t.Errorf("auth-valid cache key must include authorization header for key identity, got: %s", key)
		}
	})

	// Test 4: subscription-valid cache key must match subscription-info for coherence (gateway policy)
	t.Run("subscription-valid matches subscription-info key", func(t *testing.T) {
		subValidKey := assertCacheKeyContains(t, gwPolicy,
			[]string{"userId", "username", "groups"},
			"spec", "defaults", "rules", "authorization", "subscription-valid", "cache", "key", "selector",
		)
		subInfoKey := assertCacheKeyContains(t, gwPolicy,
			nil,
			"spec", "defaults", "rules", "metadata", "subscription-info", "cache", "key", "selector",
		)
		if subValidKey != subInfoKey {
			t.Errorf("subscription-valid cache key should match subscription-info for cache coherence\nsubscription-valid: %s\nsubscription-info:  %s", subValidKey, subInfoKey)
		}
		if !contains(subValidKey, "x-gateway-model-name") && !contains(subValidKey, "request.path") {
			t.Errorf("subscription-valid cache key must include dynamic model identity, got: %s", subValidKey)
		}
	})

	// Test 5: require-group-membership cache key must include username, groups, and dynamic model identity.
	t.Run("require-group-membership includes username, groups, dynamic model", func(t *testing.T) {
		key := assertCacheKeyContains(t, gwPolicy,
			[]string{"username", "groups", "join"},
			"spec", "defaults", "rules", "authorization", "require-group-membership", "cache", "key", "selector",
		)
		if !contains(key, "x-gateway-model-name") && !contains(key, "request.path") {
			t.Errorf("require-group-membership cache key must include dynamic model identity (header or path), got: %s", key)
		}
	})
}

// TestMaaSAuthPolicyReconciler_CacheKeyModelIsolation verifies per-model cache key isolation.
//
// After the gateway-level AuthPolicy refactor, model isolation strategy changes:
//   - Gateway policy (singleton): subscription-info/auth-valid/subscription-valid use dynamic
//     CEL (X-Gateway-Model-Name header or path) for runtime isolation — the same CEL expression
//     appears in both model-1 and model-2 scenarios because they share the gateway policy.
//   - Group policies (per-model): require-group-membership still bakes in static namespace/name,
//     so keys differ between models at compile time.
func TestMaaSAuthPolicyReconciler_CacheKeyModelIsolation(t *testing.T) {
	const (
		namespace = "default"
		gatewayNS = "gateway-ns"
	)

	model1Name := "llm-1"
	model2Name := "llm-2"

	model1 := newMaaSModelRef(model1Name, namespace, "ExternalModel", model1Name)
	route1 := newHTTPRoute(model1Name, namespace)
	policy1 := newMaaSAuthPolicy("policy-1", namespace, "team-a", maasv1alpha1.ModelRef{Name: model1Name, Namespace: namespace})

	model2 := newMaaSModelRef(model2Name, namespace, "ExternalModel", model2Name)
	route2 := newHTTPRoute(model2Name, namespace)
	policy2 := newMaaSAuthPolicy("policy-2", namespace, "team-a", maasv1alpha1.ModelRef{Name: model2Name, Namespace: namespace})

	c := fake.NewClientBuilder().
		WithScheme(scheme).
		WithRESTMapper(testRESTMapper()).
		WithObjects(model1, route1, policy1, model2, route2, policy2).
		WithStatusSubresource(&maasv1alpha1.MaaSAuthPolicy{}).
		Build()

	r := &MaaSAuthPolicyReconciler{
		Client:           c,
		Scheme:           scheme,
		MaaSAPINamespace: "maas-system",
		GatewayName:      "maas-default-gateway",
		GatewayNamespace: gatewayNS,
		MetadataCacheTTL: 60,
		AuthzCacheTTL:    60,
	}

	req1 := ctrl.Request{NamespacedName: types.NamespacedName{Name: "policy-1", Namespace: namespace}}
	if _, err := r.Reconcile(context.Background(), req1); err != nil {
		t.Fatalf("Reconcile policy-1: %v", err)
	}
	req2 := ctrl.Request{NamespacedName: types.NamespacedName{Name: "policy-2", Namespace: namespace}}
	if _, err := r.Reconcile(context.Background(), req2); err != nil {
		t.Fatalf("Reconcile policy-2: %v", err)
	}

	// Singleton gateway policy: subscription-info/auth-valid/subscription-valid use dynamic
	// celModelIdentity for runtime isolation, so the CEL expression is the same string in
	// both reconciles (they're writing to the same policy). Verify it contains the model
	// identity extractor expression rather than static model names.
	gwPolicy := &unstructured.Unstructured{}
	gwPolicy.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
	if err := c.Get(context.Background(), types.NamespacedName{Name: "maas-gateway-auth", Namespace: gatewayNS}, gwPolicy); err != nil {
		t.Fatalf("Get gateway AuthPolicy: %v", err)
	}

	gatewayEvaluators := []struct {
		name string
		path []string
	}{
		{"subscription-info", []string{"spec", "defaults", "rules", "metadata", "subscription-info", "cache", "key", "selector"}},
		{"auth-valid", []string{"spec", "defaults", "rules", "authorization", "auth-valid", "cache", "key", "selector"}},
		{"subscription-valid", []string{"spec", "defaults", "rules", "authorization", "subscription-valid", "cache", "key", "selector"}},
	}

	for _, eval := range gatewayEvaluators {
		t.Run(eval.name+" isolates models", func(t *testing.T) {
			key, found, err := unstructured.NestedString(gwPolicy.Object, eval.path...)
			if err != nil || !found {
				t.Fatalf("gateway %s cache key missing: found=%v err=%v", eval.name, found, err)
			}
			// Gateway policy uses dynamic CEL for runtime model isolation
			if !contains(key, "x-gateway-model-name") && !contains(key, "request.path") {
				t.Errorf("gateway %s cache key must include dynamic model identity (header or path) for runtime isolation, got: %s", eval.name, key)
			}
		})
	}

	t.Run("require-group-membership isolates models", func(t *testing.T) {
		path := []string{"spec", "defaults", "rules", "authorization", "require-group-membership", "cache", "key", "selector"}
		key, found, err := unstructured.NestedString(gwPolicy.Object, path...)
		if err != nil || !found {
			t.Fatalf("gateway require-group-membership cache key missing: found=%v err=%v", found, err)
		}
		if !contains(key, "x-gateway-model-name") && !contains(key, "request.path") {
			t.Errorf("require-group-membership cache key must include dynamic model identity for runtime isolation, got: %s", key)
		}
		if !contains(key, "username") || !contains(key, "groups") {
			t.Errorf("require-group-membership cache key must include caller identity dimensions, got: %s", key)
		}
	})
}

// TestMaaSAuthPolicyReconciler_IdentityHeadersUpstream verifies that identity headers
// (X-MaaS-Username, X-MaaS-Group, X-MaaS-Subscription) are injected into requests forwarded
// to upstream workloads for the consolidated gateway-level auth policy.
// All identity information is also available to TRLP and telemetry via filters.identity.
//
// After the gateway-level refactor, response shaping lives in the singleton gateway policy
// under spec.defaults.rules.response.
func TestMaaSAuthPolicyReconciler_IdentityHeadersUpstream(t *testing.T) {
	const (
		modelName      = "llm"
		namespace      = "default"
		gatewayNS      = "gateway-ns"
		httpRouteName  = modelName
		maasPolicyName = "policy-a"
	)

	model := newMaaSModelRef(modelName, namespace, "ExternalModel", modelName)
	route := newHTTPRoute(httpRouteName, namespace)
	maasPolicy := newMaaSAuthPolicy(maasPolicyName, namespace, "team-a", maasv1alpha1.ModelRef{Name: modelName, Namespace: namespace})

	c := fake.NewClientBuilder().
		WithScheme(scheme).
		WithRESTMapper(testRESTMapper()).
		WithObjects(model, route, maasPolicy).
		WithStatusSubresource(&maasv1alpha1.MaaSAuthPolicy{}).
		Build()

	r := &MaaSAuthPolicyReconciler{
		Client:           c,
		Scheme:           scheme,
		MaaSAPINamespace: "maas-system",
		GatewayName:      "maas-default-gateway",
		GatewayNamespace: gatewayNS,
		MetadataCacheTTL: 60,
		AuthzCacheTTL:    60,
	}

	req := ctrl.Request{NamespacedName: types.NamespacedName{Name: maasPolicyName, Namespace: namespace}}
	if _, err := r.Reconcile(context.Background(), req); err != nil {
		t.Fatalf("Reconcile: unexpected error: %v", err)
	}

	// Response shaping lives in the gateway policy
	gwPolicy := &unstructured.Unstructured{}
	gwPolicy.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
	if err := c.Get(context.Background(), types.NamespacedName{Name: "maas-gateway-auth", Namespace: gatewayNS}, gwPolicy); err != nil {
		t.Fatalf("Get gateway AuthPolicy: %v", err)
	}

	// Test 1: Verify identity headers are forwarded upstream for consolidated gateway auth
	t.Run("identity headers forwarded to upstream", func(t *testing.T) {
		headers, found, err := unstructured.NestedMap(gwPolicy.Object, "spec", "defaults", "rules", "response", "success", "headers")
		if err != nil {
			t.Fatalf("Error checking headers: %v", err)
		}
		if !found {
			t.Fatalf("response.success.headers should exist")
		}

		requiredHeaders := []string{
			"X-MaaS-Username", "X-MaaS-Username-Token",
			"X-MaaS-Group", "X-MaaS-Group-Token",
			"X-MaaS-Subscription",
		}
		for _, header := range requiredHeaders {
			if _, exists := headers[header]; !exists {
				t.Errorf("Identity header %q should be present in gateway response headers", header)
			}
		}

		if _, exists := headers["Authorization"]; exists {
			t.Errorf("Authorization header should NOT be stripped (needed by FilterModelsByAccess)")
		}
	})

	// Test 2: Verify filters.identity exists and contains all necessary data for TRLP and telemetry
	t.Run("identity data available for TRLP and telemetry", func(t *testing.T) {
		identity, found, err := unstructured.NestedMap(gwPolicy.Object, "spec", "defaults", "rules", "response", "success", "filters", "identity", "json", "properties")
		if err != nil || !found {
			t.Fatalf("filters.identity.json.properties missing: found=%v err=%v", found, err)
		}

		requiredFields := []string{
			"userid",
			"groups",
			"selected_subscription_key",
			"selected_subscription",
			"subscription_info",
		}
		for _, field := range requiredFields {
			if _, exists := identity[field]; !exists {
				t.Errorf("filters.identity must include %q for TRLP/telemetry, but it's missing", field)
			}
		}
		for _, field := range []string{"keyId"} {
			if _, exists := identity[field]; !exists {
				t.Errorf("filters.identity should include %q for observability, but it's missing", field)
			}
		}

		subscriptionInfoField, exists := identity["subscription_info"]
		if !exists {
			t.Error("filters.identity must include 'subscription_info' field")
		} else {
			subscriptionInfoMap, ok := subscriptionInfoField.(map[string]any)
			if !ok {
				t.Errorf("subscription_info should be a map, got %T", subscriptionInfoField)
			} else {
				expr, hasExpr := subscriptionInfoMap["expression"]
				if !hasExpr {
					t.Error("subscription_info should have an 'expression' field")
				} else {
					exprStr, ok := expr.(string)
					if !ok {
						t.Errorf("subscription_info expression should be a string, got %T", expr)
					} else if !contains(exprStr, `auth.metadata["subscription-info"]`) {
						t.Errorf("subscription_info expression should reference full subscription-info object, got: %s", exprStr)
					}
				}
			}
		}
	})

	// Test 3: Verify metrics are enabled on identity filter
	t.Run("identity filter has metrics enabled", func(t *testing.T) {
		metricsEnabled, found, err := unstructured.NestedBool(gwPolicy.Object, "spec", "defaults", "rules", "response", "success", "filters", "identity", "metrics")
		if err != nil || !found {
			t.Fatalf("filters.identity.metrics missing: found=%v err=%v", found, err)
		}
		if !metricsEnabled {
			t.Error("filters.identity.metrics must be true for telemetry to access identity data")
		}
	})
}

func TestBuildGatewayAuthPolicySpec_K8sAndOIDCAuth(t *testing.T) {
	r := &MaaSAuthPolicyReconciler{
		MaaSAPINamespace: "maas-system",
		GatewayName:      "maas-default-gateway",
		GatewayNamespace: "gateway-ns",
		ClusterAudience:  "https://kubernetes.default.svc",
		MetadataCacheTTL: 60,
		AuthzCacheTTL:    60,
	}

	gwSpecToUnstructured := func(t *testing.T, spec map[string]any) *unstructured.Unstructured {
		t.Helper()
		obj := &unstructured.Unstructured{Object: map[string]any{"spec": spec}}
		return obj
	}

	t.Run("without OIDC", func(t *testing.T) {
		spec := r.buildGatewayAuthPolicySpec("{}", nil, "", "models-as-a-service", "test-gateway-ns", "test-gateway")
		obj := gwSpecToUnstructured(t, spec)

		auth, found, err := unstructured.NestedMap(obj.Object, "spec", "defaults", "rules", "authentication")
		if err != nil || !found {
			t.Fatalf("authentication block missing: found=%v err=%v", found, err)
		}
		if _, exists := auth["api-keys"]; !exists {
			t.Error("api-keys authentication should always be present")
		}
		if _, exists := auth["openshift-identities"]; !exists {
			t.Error("openshift-identities should always be present")
		}
		if _, exists := auth["oidc-identities"]; exists {
			t.Error("oidc-identities should NOT be present when OIDC config is nil")
		}
	})

	t.Run("with OIDC", func(t *testing.T) {
		oidc := &oidcConfig{
			IssuerURL: "https://keycloak.example.com/realms/test",
			ClientID:  "maas-client",
		}
		spec := r.buildGatewayAuthPolicySpec("{}", oidc, "", "models-as-a-service", "test-gateway-ns", "test-gateway")
		obj := gwSpecToUnstructured(t, spec)

		auth, found, err := unstructured.NestedMap(obj.Object, "spec", "defaults", "rules", "authentication")
		if err != nil || !found {
			t.Fatalf("authentication block missing: found=%v err=%v", found, err)
		}
		if _, exists := auth["oidc-identities"]; !exists {
			t.Fatal("oidc-identities should be present when OIDC config is provided")
		}
		issuer, found, err := unstructured.NestedString(obj.Object, "spec", "defaults", "rules", "authentication", "oidc-identities", "jwt", "issuerUrl")
		if err != nil || !found {
			t.Fatalf("oidc issuerUrl missing: found=%v err=%v", found, err)
		}
		if issuer != oidc.IssuerURL {
			t.Errorf("oidc issuerUrl = %v, want %v", issuer, oidc.IssuerURL)
		}
	})

	t.Run("subscription-info has model-route scoped when condition", func(t *testing.T) {
		spec := r.buildGatewayAuthPolicySpec("{}", nil, "", "models-as-a-service", "test-gateway-ns", "test-gateway")
		obj := gwSpecToUnstructured(t, spec)

		when, found, err := unstructured.NestedSlice(obj.Object, "spec", "defaults", "rules", "metadata", "subscription-info", "when")
		if err != nil || !found || len(when) == 0 {
			t.Fatalf("subscription-info when condition missing: found=%v err=%v", found, err)
		}
		firstWhen, ok := when[0].(map[string]any)
		if !ok {
			t.Fatalf("subscription-info when[0] is not a map: %T", when[0])
		}
		pred, ok := firstWhen["predicate"].(string)
		if !ok {
			t.Fatal("subscription-info when[0] has no predicate string")
		}
		if !contains(pred, "x-gateway-model-name") || !contains(pred, "maas-api") || !contains(pred, "v1") {
			t.Errorf("subscription-info when should scope to model routes and exclude management paths, got: %s", pred)
		}
		if contains(pred, `startsWith("/llm/")`) {
			t.Errorf("subscription-info when should not be hard-coded to /llm/ routes, got: %s", pred)
		}
	})

	t.Run("subscription-valid has model-route scoped when condition", func(t *testing.T) {
		spec := r.buildGatewayAuthPolicySpec("{}", nil, "", "models-as-a-service", "test-gateway-ns", "test-gateway")
		obj := gwSpecToUnstructured(t, spec)

		when, found, err := unstructured.NestedSlice(obj.Object, "spec", "defaults", "rules", "authorization", "subscription-valid", "when")
		if err != nil || !found || len(when) == 0 {
			t.Fatalf("subscription-valid when condition missing: found=%v err=%v", found, err)
		}
		firstWhen, ok := when[0].(map[string]any)
		if !ok {
			t.Fatalf("subscription-valid when[0] is not a map: %T", when[0])
		}
		pred, ok := firstWhen["predicate"].(string)
		if !ok {
			t.Fatal("subscription-valid when[0] has no predicate string")
		}
		if !contains(pred, "x-gateway-model-name") || !contains(pred, "maas-api") || !contains(pred, "v1") {
			t.Errorf("subscription-valid when should scope to model routes and exclude management paths, got: %s", pred)
		}
		if contains(pred, `startsWith("/llm/")`) {
			t.Errorf("subscription-valid when should not be hard-coded to /llm/ routes, got: %s", pred)
		}
	})

	t.Run("require-group-membership recognizes tenant model paths", func(t *testing.T) {
		spec := r.buildGatewayAuthPolicySpec("{}", nil, "", "models-as-a-service", "test-gateway-ns", "test-gateway")
		obj := gwSpecToUnstructured(t, spec)

		rego, found, err := unstructured.NestedString(obj.Object, "spec", "defaults", "rules", "authorization", "require-group-membership", "opa", "rego")
		if err != nil || !found {
			t.Fatalf("require-group-membership rego missing: found=%v err=%v", found, err)
		}
		if !contains(rego, `path_parts[0] != "maas-api"`) || !contains(rego, `path_parts[0] != "v1"`) {
			t.Errorf("require-group-membership rego should treat tenant model paths as model routes and exclude management paths, got: %s", rego)
		}
		if contains(rego, `startswith(request_path, "/llm/")`) {
			t.Errorf("require-group-membership rego should not be hard-coded to /llm/ routes, got: %s", rego)
		}
	})

	t.Run("auth-valid supports non-API-key tokens", func(t *testing.T) {
		spec := r.buildGatewayAuthPolicySpec("{}", nil, "", "models-as-a-service", "test-gateway-ns", "test-gateway")
		obj := gwSpecToUnstructured(t, spec)

		rego, found, err := unstructured.NestedString(obj.Object, "spec", "defaults", "rules", "authorization", "auth-valid", "opa", "rego")
		if err != nil || !found {
			t.Fatalf("auth-valid rego missing: found=%v err=%v", found, err)
		}
		if !contains(rego, "not input.auth.metadata.apiKeyValidation") {
			t.Errorf("auth-valid rego should allow non-API-key tokens, got: %s", rego)
		}
	})
}

// contains is a helper to check if a string contains a substring (case-sensitive).
// assertCacheKeyContains fetches a nested string from an unstructured object and asserts it
// contains each of the required substrings. It is a test helper that reduces cyclomatic
// complexity in cache-key verification tests by collapsing NestedString + contains checks.
func assertCacheKeyContains(t *testing.T, obj *unstructured.Unstructured, required []string, path ...string) string {
	t.Helper()
	val, found, err := unstructured.NestedString(obj.Object, path...)
	if err != nil || !found {
		t.Fatalf("cache key at path %v missing: found=%v err=%v", path, found, err)
	}
	for _, sub := range required {
		if !contains(val, sub) {
			t.Errorf("cache key must contain %q, got: %s", sub, val)
		}
	}
	return val
}

func contains(s, substr string) bool {
	return len(s) >= len(substr) && (s == substr || len(substr) == 0 ||
		func() bool {
			for i := 0; i <= len(s)-len(substr); i++ {
				if s[i:i+len(substr)] == substr {
					return true
				}
			}
			return false
		}())
}

// TestMaaSAuthPolicyReconciler_MissingModelRef_FailedPhase verifies that an auth policy
// with all missing model refs gets Failed phase.
func TestMaaSAuthPolicyReconciler_MissingModelRef_FailedPhase(t *testing.T) {
	const (
		namespace    = "default"
		maasAuthName = "auth-missing"
		missingModel = "non-existent-model"
	)

	// Create auth policy referencing a non-existent model
	maasAuth := newMaaSAuthPolicy(maasAuthName, namespace, "team-a",
		maasv1alpha1.ModelRef{Name: missingModel, Namespace: namespace})

	c := fake.NewClientBuilder().
		WithScheme(scheme).
		WithRESTMapper(testRESTMapper()).
		WithObjects(maasAuth).
		WithStatusSubresource(&maasv1alpha1.MaaSAuthPolicy{}).
		Build()

	r := &MaaSAuthPolicyReconciler{
		Client:           c,
		Scheme:           scheme,
		MaaSAPINamespace: namespace,
		GatewayName:      "openshift-ingress/maas-default-gateway",
	}
	req := ctrl.Request{NamespacedName: types.NamespacedName{Name: maasAuthName, Namespace: namespace}}
	if _, err := r.Reconcile(context.Background(), req); err != nil {
		t.Fatalf("Reconcile: unexpected error: %v", err)
	}

	// Fetch updated auth policy
	var policy maasv1alpha1.MaaSAuthPolicy
	if err := c.Get(context.Background(), req.NamespacedName, &policy); err != nil {
		t.Fatalf("Get MaaSAuthPolicy: %v", err)
	}

	// Verify phase is Failed (all models missing)
	if policy.Status.Phase != maasv1alpha1.PhaseFailed {
		t.Errorf("expected phase Failed, got %q", policy.Status.Phase)
	}

	// Verify Ready condition is False
	readyCond := apimeta.FindStatusCondition(policy.Status.Conditions, "Ready")
	if readyCond == nil {
		t.Fatal("Ready condition not found")
	}
	if readyCond.Status != metav1.ConditionFalse {
		t.Errorf("expected Ready=False, got %v", readyCond.Status)
	}
}

// TestMaaSAuthPolicyReconciler_PartialModelRefs_DegradedPhase verifies that an auth policy
// with some valid and some invalid model refs gets Degraded phase.
func TestMaaSAuthPolicyReconciler_PartialModelRefs_DegradedPhase(t *testing.T) {
	const (
		namespace     = "default"
		maasAuthName  = "auth-partial"
		validModel    = "valid-model"
		missingModel  = "missing-model"
		httpRouteName = validModel
	)

	// Create valid model and route
	model := newMaaSModelRef(validModel, namespace, "ExternalModel", validModel)
	route := newHTTPRoute(httpRouteName, namespace)

	// Create auth policy referencing both valid and invalid models
	maasAuth := newMaaSAuthPolicy(maasAuthName, namespace, "team-a",
		maasv1alpha1.ModelRef{Name: validModel, Namespace: namespace},
		maasv1alpha1.ModelRef{Name: missingModel, Namespace: namespace})

	c := fake.NewClientBuilder().
		WithScheme(scheme).
		WithRESTMapper(testRESTMapper()).
		WithObjects(model, route, maasAuth).
		WithStatusSubresource(&maasv1alpha1.MaaSAuthPolicy{}).
		Build()

	r := &MaaSAuthPolicyReconciler{
		Client:           c,
		Scheme:           scheme,
		MaaSAPINamespace: namespace,
		GatewayName:      "openshift-ingress/maas-default-gateway",
	}
	req := ctrl.Request{NamespacedName: types.NamespacedName{Name: maasAuthName, Namespace: namespace}}
	if _, err := r.Reconcile(context.Background(), req); err != nil {
		t.Fatalf("Reconcile: unexpected error: %v", err)
	}

	var policy maasv1alpha1.MaaSAuthPolicy
	if err := c.Get(context.Background(), req.NamespacedName, &policy); err != nil {
		t.Fatalf("Get MaaSAuthPolicy: %v", err)
	}

	// Verify phase is Degraded (partial functionality)
	if policy.Status.Phase != maasv1alpha1.PhaseDegraded {
		t.Errorf("expected phase Degraded, got %q", policy.Status.Phase)
	}

	// Verify Ready condition is False with PartialFailure reason
	readyCond := apimeta.FindStatusCondition(policy.Status.Conditions, "Ready")
	if readyCond == nil {
		t.Fatal("Ready condition not found")
	}
	if readyCond.Status != metav1.ConditionFalse {
		t.Errorf("expected Ready=False, got %v", readyCond.Status)
	}
	if readyCond.Reason != "PartialFailure" {
		t.Errorf("expected reason PartialFailure, got %q", readyCond.Reason)
	}
}

// TestMaaSAuthPolicyReconciler_AllValidModelRefs_ActivePhase verifies that an auth policy
// with all valid model refs and accepted/enforced AuthPolicy gets Active phase.
func TestMaaSAuthPolicyReconciler_AllValidModelRefs_ActivePhase(t *testing.T) {
	const (
		namespace      = "default"
		maasAuthName   = "auth-valid"
		modelName      = "valid-model"
		httpRouteName  = modelName
		authPolicyName = "maas-auth-" + modelName
	)

	model := newMaaSModelRef(modelName, namespace, "ExternalModel", modelName)
	route := newHTTPRoute(httpRouteName, namespace)
	maasAuth := newMaaSAuthPolicy(maasAuthName, namespace, "team-a",
		maasv1alpha1.ModelRef{Name: modelName, Namespace: namespace})

	// Pre-create AuthPolicy with Accepted=True and Enforced=True (simulates Kuadrant accepting)
	existingAP := newPreexistingAuthPolicy(authPolicyName, namespace, modelName, map[string]string{
		"maas.opendatahub.io/auth-policies": maasAuthName,
	})
	if err := unstructured.SetNestedSlice(existingAP.Object, []any{
		map[string]any{
			"type":   "Accepted",
			"status": "True",
		},
		map[string]any{
			"type":   "Enforced",
			"status": "True",
		},
	}, "status", "conditions"); err != nil {
		t.Fatalf("SetNestedSlice status.conditions: %v", err)
	}

	c := fake.NewClientBuilder().
		WithScheme(scheme).
		WithRESTMapper(testRESTMapper()).
		WithObjects(model, route, maasAuth, existingAP).
		WithStatusSubresource(&maasv1alpha1.MaaSAuthPolicy{}).
		Build()

	r := &MaaSAuthPolicyReconciler{
		Client:           c,
		Scheme:           scheme,
		MaaSAPINamespace: namespace,
		GatewayName:      "openshift-ingress/maas-default-gateway",
	}
	req := ctrl.Request{NamespacedName: types.NamespacedName{Name: maasAuthName, Namespace: namespace}}
	if _, err := r.Reconcile(context.Background(), req); err != nil {
		t.Fatalf("Reconcile: unexpected error: %v", err)
	}

	var policy maasv1alpha1.MaaSAuthPolicy
	if err := c.Get(context.Background(), req.NamespacedName, &policy); err != nil {
		t.Fatalf("Get MaaSAuthPolicy: %v", err)
	}

	// Verify phase is Active
	if policy.Status.Phase != maasv1alpha1.PhaseActive {
		t.Errorf("expected phase Active, got %q", policy.Status.Phase)
	}

	// Verify Ready condition is True
	readyCond := apimeta.FindStatusCondition(policy.Status.Conditions, "Ready")
	if readyCond == nil {
		t.Fatal("Ready condition not found")
	}
	if readyCond.Status != metav1.ConditionTrue {
		t.Errorf("expected Ready=True, got %v", readyCond.Status)
	}

	// Gateway-only mode no longer populates per-model authPolicies status entries.
	if len(policy.Status.AuthPolicies) != 0 {
		t.Fatalf("expected no per-model authPolicy status entries, got %d", len(policy.Status.AuthPolicies))
	}
}

// TestMaaSAuthPolicyReconciler_NoSpec verifies that a legacy auth policy created
// without a spec field is marked Failed without adding a finalizer.
func TestMaaSAuthPolicyReconciler_NoSpec(t *testing.T) {
	const namespace = "default"

	policy := &maasv1alpha1.MaaSAuthPolicy{
		ObjectMeta: metav1.ObjectMeta{Name: "no-spec", Namespace: namespace},
	}

	c := fake.NewClientBuilder().
		WithScheme(scheme).
		WithRESTMapper(testRESTMapper()).
		WithObjects(policy).
		WithStatusSubresource(&maasv1alpha1.MaaSAuthPolicy{}).
		Build()

	r := &MaaSAuthPolicyReconciler{Client: c, Scheme: scheme, MaaSAPINamespace: "maas-system"}
	req := ctrl.Request{NamespacedName: types.NamespacedName{Name: policy.Name, Namespace: namespace}}
	if _, err := r.Reconcile(context.Background(), req); err != nil {
		t.Fatalf("Reconcile: unexpected error: %v", err)
	}

	got := &maasv1alpha1.MaaSAuthPolicy{}
	if err := c.Get(context.Background(), req.NamespacedName, got); err != nil {
		t.Fatalf("Get policy: %v", err)
	}

	if len(got.Finalizers) > 0 {
		t.Errorf("expected no finalizers, got %v", got.Finalizers)
	}

	if got.Status.Phase != maasv1alpha1.PhaseInvalid {
		t.Errorf("phase = %q, want %q", got.Status.Phase, maasv1alpha1.PhaseInvalid)
	}

	ready := apimeta.FindStatusCondition(got.Status.Conditions, "Ready")
	if ready == nil {
		t.Fatal("Ready condition not found")
	}
	if ready.Status != metav1.ConditionFalse {
		t.Errorf("Ready.Status = %q, want %q", ready.Status, metav1.ConditionFalse)
	}
	if ready.Reason != string(maasv1alpha1.ReasonInvalidSpec) {
		t.Errorf("Ready.Reason = %q, want %q", ready.Reason, maasv1alpha1.ReasonInvalidSpec)
	}
	if !strings.Contains(ready.Message, "spec is required") {
		t.Errorf("Ready.Message = %q, expected it to contain %q", ready.Message, "spec is required")
	}
}

// TestMaaSAuthPolicyReconciler_StaleEvent_NoOp verifies the W4a contract: a reconcile
// request for a MaaSAuthPolicy that no longer exists (stale queue entry or deleted-race)
// returns cleanly without error. After the W4a fix, fetchOIDCConfig is only called after
// confirming the policy CR exists, so the Tenant is not queried on stale events.
func TestMaaSAuthPolicyReconciler_StaleEvent_NoOp(t *testing.T) {
	// Empty store — policy was deleted before this reconcile fired.
	c := fake.NewClientBuilder().
		WithScheme(scheme).
		WithRESTMapper(testRESTMapper()).
		Build()

	r := &MaaSAuthPolicyReconciler{Client: c, Scheme: scheme, MaaSAPINamespace: "maas-system"}
	req := ctrl.Request{NamespacedName: types.NamespacedName{Name: "gone-policy", Namespace: "default"}}

	res, err := r.Reconcile(context.Background(), req)
	if err != nil {
		t.Fatalf("expected no error for stale event, got: %v", err)
	}
	if res != (ctrl.Result{}) {
		t.Errorf("expected empty Result, got %+v", res)
	}
}
