resources:
  - clusterrole.yaml
  - clusterrole_binding.yaml
  - service_account.yaml
  - leader_election_role.yaml
  - leader_election_role_binding.yaml
  - secret_reader_role.yaml
  - secret_reader_role_binding.yaml
